name: Build phrase database
on:
  push:
    paths:
      - 'Source/Data/**'
      - '.github/workflows/continuous-build-data.yml'
  pull_request:
    paths:
      - 'Source/Data/**'
      - '.github/workflows/continuous-build-data.yml'

jobs:
  build:
    name: Build phrase database
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: '3.12'
      - name: Build phrase database
        run: make
        working-directory: Source/Data
