name: Build
on:
  push:
    paths:
      - 'Source/Data/**'
  pull_request:
    paths:
      - 'Source/Data/**'

jobs:
  build:
    name: Build phrase database
    runs-on: macOS-15
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: '3.12'
      - name: Build phrase database
        run: make
        working-directory: Source/Data
